# Streamlit Secrets Configuration
# Add your API keys and sensitive information here
# This file should NOT be committed to version control

# Google Gemini API Key (Free tier available)
# Get your free API key at: https://makersuite.google.com/app/apikey
GOOGLE_API_KEY = "AIzaSyAnE6jz-3Fzkw-cBZ9ninztC5xCCIx5INs"

# Hugging Face API Token (Free - Optional for better performance)
# Get your free token at: https://huggingface.co/settings/tokens
HUGGINGFACE_TOKEN = "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"

# Other API Options (all optional):
# -----------------------------------
# Replicate API Token - https://replicate.com (free tier available)
# REPLICATE_API_TOKEN = ""

# Stability AI - https://platform.stability.ai (paid)
# STABILITY_API_KEY = ""